# Описываем Виртуальные машины
MACHINES = {
  :"Lesson3" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 2048,
    :vm_name => "Lesson3"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "public_network"
    config.vm.synced_folder "Q:/1VirtualBox/vagrant/.vagrant/ssh/ansible", "/vagrant/ssh/ansible"
    
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Создание дополнительных дисков
      box.vm.disk :disk, size: "512MB", name: "disk1"
      box.vm.disk :disk, size: "512MB", name: "disk2"
      box.vm.disk :disk, size: "512MB", name: "disk3"
      box.vm.disk :disk, size: "512MB", name: "disk4"

      # Генерация ssh ключей 
      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        # Копирование публичного ключа Ansible сервера в authorized_keys
        cat /vagrant/ssh/ansible/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        systemctl restart sshd
      SHELL
    end
  end
end
