# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define "nfss" do |nfss|
    nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    nfss.vm.hostname = "nfss"
    nfss.vm.provision "shell", inline: <<-SHELL
      apt install -y nfs-kernel-server
      mkdir -p /srv/share/upload
      chown -R nobody:nogroup /srv/share
      chmod 0777 /srv/share/upload
      cat <<EOF > /etc/exports
/srv/share 192.168.50.11/32(rw,sync,root_squash)
EOF
      exportfs -ra
      systemctl restart nfs-kernel-server
      echo "ДЗ по NFS выполнено!" > /srv/share/upload/check_file.txt
    SHELL
  end

  config.vm.define "nfsc" do |nfsc|
    nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
    nfsc.vm.hostname = "nfsc"
    nfsc.vm.provision "shell", inline: <<-SHELL
      apt install -y nfs-common
      mkdir -p /mnt/nfs
      echo "192.168.50.10:/srv/share /mnt/nfs nfs vers=3,noauto,x-systemd.automount 0 0" >> /etc/fstab
      systemctl daemon-reload
      systemctl restart remote-fs.target
    SHELL
  end
end
