MACHINES = {
  :"Lesson5" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 2048,
    :vm_name => "Lesson5"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "public_network", bridge: "Ethernet"

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      box.vm.disk :disk, size: "512MB", name: "disk1"
      box.vm.disk :disk, size: "512MB", name: "disk2"
      box.vm.disk :disk, size: "512MB", name: "disk3"
      box.vm.disk :disk, size: "512MB", name: "disk4"
      box.vm.disk :disk, size: "512MB", name: "disk5"
      box.vm.disk :disk, size: "512MB", name: "disk6"
      box.vm.disk :disk, size: "512MB", name: "disk7"
      box.vm.disk :disk, size: "512MB", name: "disk8"
      box.vm.disk :disk, size: "512MB", name: "disk9"

      box.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get upgrade -y
        apt-get install -y wget zfsutils-linux
        wget http://raw.githubusercontent.com/Sveryatelin/Home_work_OTUS_LP/refs/heads/main/Lesson5/Script.sh -O /home/vagrant/Script.sh
        chmod +x /home/vagrant/Script.sh
      SHELL
    end
  end
end
