# Описываем виртуальные машины
MACHINES = {
  :"Lesson5" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 2048,
    :vm_name => "Lesson5"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем синхронизацию папки
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.network "public_network", bridge: "Ethernet"

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      # Настройка ресурсов ВМ
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Добавление дополнительных дисков
      box.vm.disk :disk, size: "512MB", name: "disk1"
      box.vm.disk :disk, size: "512MB", name: "disk2"
      box.vm.disk :disk, size: "512MB", name: "disk3"
      box.vm.disk :disk, size: "512MB", name: "disk4"
      box.vm.disk :disk, size: "512MB", name: "disk5"
      box.vm.disk :disk, size: "512MB", name: "disk6"
      box.vm.disk :disk, size: "512MB", name: "disk7"
      box.vm.disk :disk, size: "512MB", name: "disk8"
      box.vm.disk :disk, size: "512MB", name: "disk9"

      # Провизия для установки пакетов
      box.vm.provision "shell", inline: <<-SHELL
        # Обновление системы и установка базовых утилит
        apt-get update -y
        apt-get upgrade -y
        apt-get install -y wget zfsutils-linux
      SHELL
    end
  end
end
